import Head from 'next/head'

const Seo = () => {
  return (
    <Head>
      <title>Create Next App</title>
      <meta name='description' content='Generated by create next app' />
      <meta name='viewport' content='width=device-width, initial-scale=1' />
    </Head>
  )
}
export default Seo
